### ISSUE TITLE
`security-jwt` feature generates an incorrect YAML

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-starter#1218]
While testing https://github.com/micronaut-projects/micronaut-aot/issues/109 we realised that the `security-jwt` feature generates an incorrect YAML:

https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_11&lang=JAVA&build=GRADLE&test=JUNIT&features=security-jwt&version=3.4.3&activity=preview&showing=/src/main/resources/application.yml

```yaml
micronaut:
  application:
    name: demo
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
netty:
  default:
    allocator:
      max-order: 3
```

The YAML itself is _syntactically_ valid, but a parser will see those quotes as:

```java
"\"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}\""
```

Which is not what we want
