### ISSUE TITLE
Add feature which generates a github actions file to build projects

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1280]
Add a new feature `github-workflow-ci`

# Gradle

see: https://github.com/gradle/gradle-build-action

In github when you go to actions and click `New Workflow`:

<img width="1288" alt="Screenshot 2022-06-03 at 12 22 12" src="https://user-images.githubusercontent.com/864788/171836522-4ece76a8-8666-4b92-94ab-a3cbd009ec42.png">

We could generate something like: 

```yaml
name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
     - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.1.7
      with:
        arguments: build
```

# Maven 

<img width="1355" alt="Screenshot 2022-06-03 at 12 23 33" src="https://user-images.githubusercontent.com/864788/171837236-c0bb7268-f258-4f15-8da6-30d332382cb1.png">

```yaml
name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./mvnw package
```
