### ISSUE TITLE
Generate test resources compatible configuration for R2DBC

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-starter#1353]
Current configuration is not compatible with test resources:

```yaml
r2dbc:
 datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: H2
      url: r2dbc:h2:mem:///testdb;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''

```
