### ISSUE TITLE
Generate MongoDB configuration compatible with test resources

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-starter#1354]
Current config generated is:

```yaml
micronaut:
  application:
    name: mongoTest
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
netty:
  default:
    allocator:
      max-order: 3
```

This is not compatible with test resources. I had to comment out the above URI to get it to work.
