### ISSUE TITLE
Question About DataSource Config Settings

### ISSUE THREAD

**Issue by jeffscottbrown** [micronaut-projects/micronaut-starter#1502]
At https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_11&lang=JAVA&build=GRADLE&test=JUNIT&features=data-jpa&features=hibernate-jpa&version=3.7.2&activity=preview&showing=/src/main/resources/application.yml is the following:

```
micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update
netty:
  default:
    allocator:
      max-order: 3
```

Notice that `datasources.default.schema-generate` is `CREATE_DROP` and `jpa.default.properties.hibernate.hbm2ddl.auto` is `update`.

I have not confirmed, but it appears that `jpa.default.properties.hibernate.hbm2ddl.auto` is respected and `datasources.default.schema-generate` may be ignored.

I asked if `datasources.default.schema-generate` should have an impact from that config and @sdelamo responded with the following:

> Probably it should be both the same. Can you create an issue?
