### ISSUE TITLE
Don't set datasources.default. schema-generate: CREATE_DROP when adding flyway

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1524]
Currently for example for `data-jdbc` and `flyway` we generate. 

```
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    schema-generate: CREATE_DROP
    dialect: H2
```

I think we should generate: 

```
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    dialect: H2
flyway:
  datasources: 
    default: 
      enabled: true 
```

Thus, removing `datasources.default. schema-generate: CREATE_DROP`
