### ISSUE TITLE
Don't set datasources.default. schema-generate: CREATE_DROP when adding liquibase

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#1525]
Currently for example for `data-jdbc` and `flyway` we generate. 

```
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    schema-generate: CREATE_DROP
    dialect: H2
```

I think we should generate: 

```
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    dialect: H2
liquibase:
    datasources: 
        default: 
            change-log: 'classpath:db/liquibase-changelog.xml'
```

Thus, removing `datasources.default. schema-generate: CREATE_DROP`

we should generate a `src/main/resources/db/liquibase-changelog.xml` file with content: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
         http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
  <include file="changelog/01-schema.xml" relativeToChangelogFile="true"/>
</databaseChangeLog>
```

and a `src/main/resources/db/01-schema.xml`

```
<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
         http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
  <changeSet id="01" author="username">
  </changeSet>
</databaseChangeLog>
```
