### ISSUE TITLE
Bad indentation in application.yml

### ISSUE THREAD

**Issue by benmccann** [micronaut-projects/micronaut-starter#155]
I created a starter project and it has bad indentation for `datasources.default` in `src/main/resources/application.yml`:

```
micronaut:
  application:
    name: micronautExample
datasources.default: {
  }
'#graphql.graphiql.enabled': true
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
```

I'm also wondering if there should actually be a pound sign as well: https://github.com/micronaut-projects/micronaut-starter/commit/1267973494d3e89eec3456da67ebc7db015af29d#r38814657
