### ISSUE TITLE
Invalid driver class name property is generated

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-starter#1650]
### Description

Generate a project using `postgres` feature, for example. The generated `application.yml` file contains:

```yaml
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
```

However the `driver-class-name` property is invalid, it should be `driverClassName`. This causes [problems when using test resources and production databases](https://github.com/micronaut-projects/micronaut-test-resources/issues/181), since the driver class name is missing and that the test resources service provides it.

**Comment by sdelamo** [comment]
`driver-class-name` should be valid. 

from the property binding section: 

https://docs.micronaut.io/latest/guide/

> Note that these property references should be in kebab case (lowercase and hyphen-separated) when placing references in code or in placeholder values. For example, use micronaut.server.default-charset and not micronaut.server.defaultCharset.

> Micronaut still allows specifying the latter in configuration, but normalizes the properties into kebab case form to optimize memory consumption and reduce complexity when resolving properties.

**Comment by melix** [comment]
Then this means that there is a bug in property resolution in Micronaut Core: it shouldn't say that the property `driverClassName` or `driver-class-name` is missing, if one of the 2 is set. The issue is that currently what we generate is kind of broken as soon as you use test resources. This isn't a criticial issue, in the sense that the "only" side effect is that we start a container when we shouldn't, but still...

**Comment by sdelamo** [comment]
> The issue is that currently what we generate is kind of broken as soon as you use test resources.

I think this is correct configuration: 

```yaml
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
```
