### ISSUE TITLE
selecting jwt and oauth2 creates incorrect configuration

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#425]
This generates: 

```yaml
micronaut:
  security:
    token:
      jwt:
        cookie:
          enabled: true
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    authentication: bearer
```

`micronaut.security.token.jwt.cookie.enabled` defaults to true. No need to configure it. 

I think we could generate something like this: 

```yaml
micronaut
  security:
    authentication: idtoken 
    oauth2:
      clients:
        changeme: 
          client-id: '${OAUTH_CLIENT_ID}'  
          client-secret: '${OAUTH_CLIENT_SECRET}' 
          openid:
            issuer: '${OAUTH_ISSUER}' 
```
